import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight:["400","500","600","700"]
});

const ovo = Ovo({
  variable: "--font-ovo",
  subsets: ["latin"],
  weight:["400"]
});

export const metadata = {
  title: "Portfolio-Roshan",
  description: "Generated by create next app",
  icons: {
    icon: "/code1.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${outfit.variable} ${ovo.variable} antialiased leading-8 overflow-x-hidden dark:bg-dark-theme dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
